// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChh6sNaEcBcKe9grUdrWNIKq7JL_ZYay0',
    appId: '1:902353413586:web:9ca9aec1ceb762adce140b',
    messagingSenderId: '902353413586',
    projectId: 'games-review-cb093',
    authDomain: 'games-review-cb093.firebaseapp.com',
    storageBucket: 'games-review-cb093.firebasestorage.app',
    measurementId: 'G-XTZPRRH79S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD67LLkb-O4oUs7UlOsVkVRzrcUKCUrld8',
    appId: '1:902353413586:android:7a834ec31ed99a1dce140b',
    messagingSenderId: '902353413586',
    projectId: 'games-review-cb093',
    storageBucket: 'games-review-cb093.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKplvxiGmq6Xes6o6v5owi6aPySgONmcg',
    appId: '1:902353413586:ios:f3fa1f5ed85ecf00ce140b',
    messagingSenderId: '902353413586',
    projectId: 'games-review-cb093',
    storageBucket: 'games-review-cb093.firebasestorage.app',
    iosBundleId: 'com.example.proyekPab2Kelompok7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKplvxiGmq6Xes6o6v5owi6aPySgONmcg',
    appId: '1:902353413586:ios:f3fa1f5ed85ecf00ce140b',
    messagingSenderId: '902353413586',
    projectId: 'games-review-cb093',
    storageBucket: 'games-review-cb093.firebasestorage.app',
    iosBundleId: 'com.example.proyekPab2Kelompok7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChh6sNaEcBcKe9grUdrWNIKq7JL_ZYay0',
    appId: '1:902353413586:web:7ca178adfb3a6c5ace140b',
    messagingSenderId: '902353413586',
    projectId: 'games-review-cb093',
    authDomain: 'games-review-cb093.firebaseapp.com',
    storageBucket: 'games-review-cb093.firebasestorage.app',
    measurementId: 'G-RD2E235NPD',
  );
}
